package kawigi.cmd;

import kawigi.ahmed_aly_unused_code_cleaner.CPPProcessor;
import kawigi.properties.PrefFactory;

public class GetSource {
	private static GetSource instance = null;

	/**
	 * Code that was first generated on entering to the problem.
	 */
	public static String autoGeneratedCode = null;
	
	public String getSource() {
		LocalTestAction.requestFileSync();

		String s = Dispatcher.getCodePane().getText();
		// If nothing was changed since auto-generation then returnin nothing.
		// This will help to generate code again if user simply changes
		// languages.
		if (autoGeneratedCode != null && s.equals(autoGeneratedCode))
			s = "";

		// Remove KawigiEdit tags. Eventually we will probably have reason to
		// replace certain KawigiEdit tags with something interesting on
		// submission.
		s = s.replaceAll("<%:[a-zA-Z0-9_-]+%>", "");
		if (
				PrefFactory.getPrefs().getBoolean("kawigi.ucc.useUCC", false)
				&&
				ProblemContext.getLanguage().getFileName("temp").toLowerCase()
				.trim().endsWith("cpp")) {
			CPPProcessor cleaner = new CPPProcessor(s);
			cleaner.cleanCode();
			s = cleaner.getCode();
		}
		return s;
	}
	
	public static GetSource getInstance() {
		if(instance == null)
			instance = new GetSource();
		return instance;
	}
	
	private GetSource() { }
}
